### ISSUE TITLE
AIP-5 Discussion: Sigmoid Rebase Function

### ISSUE THREAD

**Issue by statuskuo** [ampleforth/AIPs#16]
https://aips.ampleforth.org/AIPs/aip-5

**Comment by brandoniles** [comment]
I support this change. Briefly (and informally)--

For the "mirrored" property:
All else being equal if the market cap of ample oscillates around a particular value, the system should spend equal time above and below the price target--but that's not what we have today. If for every positive day, greater-than-1 negative days are required (as is the case now), then there is extra psychological cost in the market that's doesn't need to be present.

For the "asymptotic" property:
The farther the market price of ample gets away from the price target, the more likely the network is in an exceptional situation. But currently this is precisely when the supply changes the most! Having asymptotes on the floor and ceiling makes the network less susceptible to extreme (and rare) scenarios and creates less karma that needs to be repaid later.

For the initial parameter values:
I appreciate that the initial values don't change more than they need to. Great job on the analysis to show the rough-equivalence on the positive side. This should make this change targeted and easier to reason about, should it get deployed.

**Comment by danb1983** [comment]
Long time holder, first governance discussion. I'd like to state that I'm not exactly "against" this, but that it seems serious and I'd like to put forth the devils advocate "against" opinion or at least ask some tough questions. 

- AMPL hasn't had long enough history to know this. Very roughly looking at lifetime cycles We started at $9m cap, went down to under $1m. Up to $5m back to $1.5m. Then the "great rally, up from $9m , to $700m down to $150m over a month. Up to $500m in a brief rally of a few days. Down to $80m, and now "midway" trending up to $170m-200m (taking circulating cap , rough numbers, not exacts). Devils advocate - AMPL is unpredictable. It had one HUGE rally, the "great rally" and one serious 1+ month pull back of 80%+ loss against that.. but the previous rallies and this one combined - there's no clear pattern they are different lengths, different % increases and decreases. How can we say that "ampl isnt working" and needs smoothing. ... related:
- Devils advocate: It does work. It has worked, and it is volatile, but how do we know what will happen "if" it goes to a $4bn cap... then back to a $1bn cap, then up to $6bn and back to $2-3bn... then it "will" slowly go up to $4bn and stay steady there (speculating... this is what I/we want to happen?) and it will happen as many more markets and products (lending) on top spreading the utility out... not just a speculative trade anymore but spread utility.
- I'd like to expand on this by stating further that previous cycles have been based on "limited extra utility" - initially only 1 real market (bitfinex, ok kucoin too), and then only Uniswap. We are now entering an era with 3 dexes (uni, sushi, balancer + mooniswap + benchmark worth mentioning + bitfinex and kucoin too). The way the market will react with these 3 markets and multiple more arbitrage opportunities at the very least, as well as the mechanics of various different incentives/apy/roi in each market (I'd argue that not just being 3 more markets/incentives = 3 more mechanics, but the interplay between them will be more like 18 more things going on and influencing each other. Additionally we don't have the extra dapps/layer2 products on top yet - lending capabilities is worth highlighting specifically but there are others - when lending comes then it might be as much as 5-20% of the supply taking part here, relieving buy and sell pressure, people happy to lend their AMPL out to avoid negative rebase, others willing to bet against that going long. it *should smooth the rebases/rallies/dumps out much more (?). Additionally there are all sorts of other products which will also add utility and supply smoothing so that there are 18 things to do with ampl rather than just trading speculating on rebase - lending, derivitives, long/short (ok we have this in ftx but there will be decentralised solutions, or even just being able to buy an "anti ampl" token , a short in essence so you profit from negative rebases and lose in positive ones. And 100x other things that my limited brain can't imagine. Point being - ampl is still early and these products aren't here yet but they are coming and they alone should take care of the supply and demand extremes (?) and smooth things much more.

- Primarily this looks like a serious change, a protocol level change, almost a "fork level core change". While not against this, why isn't this just a "layer on top"? rather than a protocol change. One way I've been thinking about to possibly do this as a layer2 would be with "investment epochs" or "lockups":
Imagine a layer 2 dap with 2 investment tranches. 
Smooth Tranche: Max positive rebase is 3%. Any extra % is given to Volatile Tranche. Maximum negative rebase is 1%.
Volatile tranche: No maximum positive rebase. If positive rebase is 5% then you will receive the full 5% + your weighted share of 2% extra (from the cap on the Smooth tranche investors pool). However there is no maximum negative rebase. If the negative rebase is  over 1% negative then you LOSE even more and pay off the extra to the smooth tranche investors.
A 2 month period (or whatever.. long term though probably rather than just 1 week) LOCKUP

Something like this would 1. address the volatility concerns - we do all want smoother rides. I have a weak heart :P. But additionally provide another app, a layer 2, and give people the CHOICE to dampen their volatilty while still holding long and give some safety (or also turn the heat on for people without a pulse who want the exposure and are super-long).

Thanks for hearing me, I'm not actually against this. There are definitely smarter economists than me, the authors of this AIP for sure. But hope some of this is interesting food for thought or would be keen to hear discussion back addressing these issues.

**Comment by statuskuo** [comment]
Thanks for all the comments thus far, there is an updated version of this proposal in progress, please stay tuned.

**Comment by ahnaguib** [comment]
Updated proposal: https://github.com/ampleforth/AIPs/blob/master/AIPs/aip-5.md

**Comment by davoiceamplesense** [comment]
Some questions. (Note: These are my personal questions about the proposal as a member of the Ampleforth community and significant investor in the protocol.) 

1. As shown in the attached image, there is a notable difference in the magnitude of negative rebases between the current linear function and the proposed sigmoid curve -- even in the .90 to .95 range. 
![area_under_curve](https://user-images.githubusercontent.com/74732859/102240079-79ed3400-3ec5-11eb-8567-9bba8f85e5e6.png)

Will this proposed change cause market actors to react more strongly to the potential of a negative rebase than they are now? Could this stronger reaction cause an acceleration in price declines and even steeper daily negative rebases for holders (not traders) of the token? 

Would this increase the length of negative rebases and disadvantage holders of the token versus active traders? 

2. Can the team provide an updated "Proposed vs Current Rebase Totals" chart showing the impact of the function on the duration and impact of negative rebases of the proposed sigmoid curve? Currently, positive rebases are displayed, but negative rebases are equally as important to show a balanced picture of the potential impact of this change. 

In addition, can the y axis be revised to show "sum of daily rebases (1, 5 days, 10 days, etc.) to more clearly indicate the expected impact of the change on daily rebase volume? 

3. Will capping the upside of token supply appreciation, but increasing the downside risk of the token decrease Ample's attractiveness as a form of collateral for lending/borrowing? 

Could this reduction in upside benefit have an unintended effect of reducing the number of passive holders of the token, which provides a price floor for the token given their longer time horizon and expected benefits?

4. Although this assessment is based on one year of data -- for approximately 6 months of this period we saw Ample trading at significantly lower volumes (due to lack of awareness of the protocol). From late June to December is when trading volumes, liquidity and interest in the token has reached current levels. 

Would it be prudent to wait to propose this change once more data is collected during (Era II, June to December and beyond) where trading volumes are robust and market actors are learning to manage the rebase and learn how the protocol functions?

**Comment by Togenkyo123** [comment]
Reposting the question I asked about this topic yesterday during Amphitheater:

Wouldn't capping the max rebase with AIP-5 increase price volatility dramatically?
Basically all the excess buying (that go beyond $2) cannot be dampened with rebases anymore so it will translate into higher price fluctuations instead.

If for example there was massive demand for AMPL pushing the marketcap 10x to 3billion, since rebases are capped, we might see the higher marketcap now being reflected in price instead, like 3$ 4$ AMPL?

---

After thinking about this for a night, I'm now **in favour** of this proposal. For some reason I had assumed that rebases would going to be capped at 5%, hence the above question, but a 11% cap seems quite right to me.

I also like the fact that after this implementation, rebases are going to be stronger for prices where AMPL has spent the most time in the past, while also avoiding the extreme scenarios where very high positive rebases would overshoot the optimal supply for the market condition and then be followed by prolonged correction in supply that would last unnecessary long.

I'd like to have clarification on 3 points:

How has the 11% cap been determined? Why shouldn't the cap be 5%/10%/15%?

On the graphic for the proposed Sigmoid Rebase Curve, I don't see the 0% neutral rebase area. Is the new AIP going to eliminate the neutral zone and make AMPL **always rebase**? 
If yes, I'm very much in favour of that! 
If not, I would like to bring this up for debate since the neutral zone would nullify quite a portion of the sigmoid curve that would have otherwise resulted in stronger dynamic rebases for these price zones. 

Correct me if I'm wrong, but I believe with the current proposed same cap of 11% for both negative and positive rebases, the middleground is slightly scewed towards negative. 
It takes ~+12.36% to negate -11% and ~-10.1% to negate +11%. Shouldn't these values be considered as the caps?
Some might think this is only a minor thing, but I believe it might make a difference in the long run.

**Comment by brandoniles** [comment]
Since this issue was opened, the governance process has changed to the new forum instead of github.

The thread was eventually continued [here](https://forum.ampleforth.org/t/rebase-curve-upgrade-proposal/327) and implemented, so marking this issue closed.
