### ISSUE TITLE
ACCP-3 Discussion :: Include support for the kMPL/AMPL Uniswap liquidity pool in the Ampleforth sync() function call fired during rebase

### ISSUE THREAD

**Issue by davoiceamplesense** [ampleforth/AIPs#25]

**Comment by davoiceamplesense** [comment]
Relevant links to AmpleSense community discussions, proposals and votes related to including AMPL in the Apollo kGeyser: 

- Idea Incubator: Initial discussion and signaling poll results - [Link](https://forum.amplesense.io/ideas/ideas/which-token-should-the-dao-pair-with-kmpl-in-the-apollo-kgeyser/)

- APP-001: AmpleSense Progress Proposal developed to inform formal community voting around asset selection (AMPL / ETH / USDC) - [Link](https://bit.ly/3lIiiol)

- Community vote: Note that 1 AMPL = 0.001 kMPL voting power - [Link](https://snapshotpage.b-cdn.net/#/amplesense/proposal/QmboVwWmDt8TJxnuMbjpt39io4z3x3Y3j4TmgvkT5yJAKQ)

**Comment by The-CryptoGenie** [comment]
Ampleforth Team - please address this ASAP. The AmpleSense hub and kMPL are instrumental in growing the Ampleforth Community.

**Comment by Jabby-s** [comment]
Would love to see this happen.  Along with the release of the new geysers, this would only help to expand public knowledge and involvement.  All in Ampleforth.  Let's go.

**Comment by Kavian-av12** [comment]
I do not see the purpose of ACCP-3.

**Comment by Alinfcs** [comment]
Happy days. Looking forward to see this project going forward.

**Comment by TheRankenFile** [comment]
Lets get it done. Five days since this has been posted already? Lets move forward, and quickly. The kMPL liquidity program has already kicked off.

**Comment by Kavian-av12** [comment]
I support this and would like to see it get done. Please and thank you.

**Comment by PascalDierich** [comment]
The AmpleSense DAO is doing a lot of great work for the Ampleforth community! 
It would be beneficial to see help from the team to support their/the community's mission.

**Comment by AMPL-Warroom** [comment]
AmpleForce Unite! 

**Mission**: ACCP-3
**Status**: Awaiting approval for moon mission!
**Message**: Requesting confirmation for immediate lift-off

**Comment by Evocrypto** [comment]
Please support this project ASAP. The more use cases for AMPL, the better.

**Comment by jagtapper** [comment]
This is an important step on the path to widespread adoption for AMPL. Uniswap has by far the largest volume of all DEXes, and integrating this function will bring us closer to an elastic AMM. 

Let's do it!

**Comment by 000007** [comment]
I am stoked to be a part of this project and wish to see it succeed. Please approve. Thank you.

**Comment by Yardie1** [comment]
The guys have done a great job so far and we all appreciate the hard work they’ve put in. I was really impressed at how small a percentage in Kmpl they’ve allocated themselves and this will only help to benefit the community even more.

**Comment by SolomonSollarsNSense** [comment]
Happy to see all the genuine support for this. It means so much to us as the leadership for this community project. We wouldn't be here without this community. Honored to be in this with you all. Let's get this market going.

**Comment by Timmy-Lancaster** [comment]
This ACCP is concerning. 

I'm not a techie, but I've been in the space long enough to know that uniswap pairs can be created without permission. Imagine each token had to ask permission for a new pool creation with ETH. Why the ACCP? 

Issue 1:
**If this is a centralization issue then I'm out**. I nearly left because of the centralized action during KuCoin and a LOT of money in the D E C E N T R A L I Z E D  finance space is hoping AMPL sprints towards decentralization. This ACCP makes it appear Ampleforth requires new pairs to go through a request process. AMPL cannot grow in the lines of BTC and ETH when it cant even be freely traded. 

Issue 2:
AmpleSense and Ampleforth are one? Are the two units not in sync? Why is Ampleforth making its community go through this process? Is there a disconnect? How Ampleforth feels about AmpleSense and the other way around. 

The second issue is not as important to me as the first, but an answer from Evan will be reassuring. I'll reiterate: A LOT OF PEOPLE ARE CONCERENED ABOUT THE CENTRALIZED NATURE OF AMPLEFORTH. So please clarify if this issue is created due to centralization or a tech limitation.

**Comment by pumipatw** [comment]
@Timmy-Lancaster I get your concern about centralization, but don't worry, I can explain.

Anyone can create Uniswap V2 pairing between AMPL and any token, but Uniswap V2 keep track of token balance internally. Calling `rebase()` without calling `sync()` in pairing will leads to supply mismatch and create opportunity to exploit the different between internal and real balance. Noted that AMPL/ETH pairing is already in this.

**Comment by PascalDierich** [comment]
@Timmy-Lancaster Concerning your second point.
The AmpleSense DAO and the Ampleforth team are two different disjunct groups. They have direct communication channels though.
IMHO its better to have a public, eventhough longer process than an untransparent one.

**Comment by Sams953** [comment]
Totally for the support of ACCP-3. Once in place it will also provide  more view on kMPL and more people may join the community.

**Comment by flrebroker** [comment]
I heartily support this because a permanent solution to accounting for rebase beats a temporary fix.  New assets sometimes require small significant changes in infrastructure to succeed.

**Comment by brandoniles** [comment]
@PascalDierich: 
>IMHO its better to have a public, eventhough longer process than an untransparent one.

Yep totally agree. For all the new faces here, welcome! We're moving toward an open model of development and governance. We don't have all the pieces in place yet, but we're getting there. If you haven't been keeping up to date, you can track our progress [here](https://www.ampleforth.org/governance/). This idea is currently in [Step 2](https://aips.ampleforth.org), and I hope it can do a better job of incorporating community sentiment than we were able to before.

Regarding this issue, did you consider [Mooniswap](https://mooniswap.exchange/#/swap)? That would definitely be the better platform for this pool. They natively support elastic tokens and I might even call it an "Elastic AMM". Uniswap pools [require active notification](https://www.ampltalk.org/app/forum/technology-development-17/topic/supported-dex-pools-61/) when token balances update. As a community, I'd love it if we could start supporting platforms that support elastic tokens. All the Enceladus pools (i.e. "non-Uniswap base token" pairs) were on Mooniswap for this reason.

It sounds like it's too late for this, though. If I can be real with AmpleSense here for a minute, locking up such a large percentage of your supply into your distribution program without doing the most basic testing (or talking to either platform) was a big misstep. On top of this, incentivizing a Uniswap pool that isn't sync'ed puts your LP's funds at risk. This is not a responsible way to do blockchain development.

If users are at risk, though, we should try to reduce damage. @davoiceamplesense how long is your distribution program, is it 3 months? We could add the sync call to the orchestrator until that is complete, then I'd recommend moving to Mooniswap or another platform at that time.

**Comment by jagtapper** [comment]
@brandoniles good points about Mooniswap. But aren't they migrating to NEAR protocol?

**Comment by PascalDierich** [comment]
@brandoniles The Apollo Geyser (Uniswap kMPL/AMPL) has a runtime of **120 days**, therefore ending around mid of march.

**Comment by davoiceamplesense** [comment]
@brandoniles:

Our kGeyser runs for 120 days. 

Regarding getting the pair supported by the Orchestrator, it would be wonderful to have this completed as soon as possible, as this is:

-Required to ensure the pool is as safe as possible 
-Requested from Uniswap

It looks like there is strong community support for this to happen rapidly. 

Would it be possible to have this implemented in the next day or so? 

Thanks for moving ahead with the process so that we can have the best possible outome.

**Comment by brandoniles** [comment]
We should be able to get this queued for tomorrow. What's the pool address?

**Comment by davoiceamplesense** [comment]
Thank you for moving on this over the holiday. 

Here is the pool address: https://etherscan.io/token/0xc463f34040ad6222C1fFB03ACEbDFAAC032202d6?a=0x53b784d0fb88f53c6af76839a7eaec8e95729375

Have a great Thanksgiving.

**Comment by danb1983** [comment]
Honestly nervous about this for a few reasons:
- 2/3 of the Amplsense team are Anonymous
- there is branding infringement that confuses people however being my main worry - at a glance it looks like AmplSense IS Ampleforth - when it is not, its an external, partly anonymous team. 
- Ultimately I feel doing work for an anonymous team is an endorsement in itself. If something "goes wrong" here then Ampleforth shares the blame.
- I would be 10000% up for this if - 1. it was a public team, and not branded to look like Ampleforth itself - a perfect example is "DeFi Saver" , an external team to the Maker project whose tech saves MakerVaults from being liquidated. I would have had a huge issue there if it was called "MakerSaver" and endorsed/recommended or dev work done there by the Maker team.

**Comment by CryptoKav** [comment]
@danb1983 

Your questions can be answered by browsing the AmpleSense Hub. Our team consists of individuals who have a long history of engagement, activity and commitment to the Ampleforth community.

You can learn how the DAO functions, how it is governed and more by visiting these links:
-https://amplesense.io/docs/why-is-the-amplesense-dao-needed/
-https://forum.amplesense.io/governance-docs/

We're available on Telegram, and our Community Hub if you have further questions.

**Comment by HarryHolisticEngineer** [comment]
keep it up!

**Comment by brandoniles** [comment]
This ACCP exists because of the incentive program you've set up and locked tokens into. Is this the address?
[https://etherscan.io/address/0xa11f6e08bf2513792e5755160825e11b47850576#code](https://etherscan.io/address/0xa11f6e08bf2513792e5755160825e11b47850576#code)

If so, that code is unverified and would be a security risk for users. There are 11 other similar contracts on etherscan, but none of those are verified either. I don't think we could proceed safely until that's resolved.

**Comment by stalker474** [comment]
@brandoniles 
Hello, the ACCP isn't targeting this contract.
The contract is created by our geyser as is says on the page "This contract was created by the contract code at **0x495074b57f8f7fd1309932f8aa1f9baff1deff4f**".
Our geyser can be checked here : https://etherscan.io/address/0x495074b57f8f7fd1309932f8aa1f9baff1deff4f#code
It spawns 3 child contracts at L491.
```
_stakingPool = new TokenPool(stakingToken);
_unlockedPool = new TokenPool(distributionToken);
_lockedPool = new TokenPool(distributionToken);
```
The TokenPool contract is defined L366.
So even though **0xa11...576** isn't verified, it's source code is verifiable by looking at the parent contract.
As for the structure of our geyser, we add as little code as possible on top of the Ampleforths' audited TokenGeyser contract code by inheriting here : L896.
I'm not sure it's possible to verify child contracts, since the contracts' creator isn't a valid ethereum account?
Thank you for looking into this!

**Comment by stalker474** [comment]
@brandoniles Apparently it IS possible to verify child contracts now.
It's been done, you'll be able to review the source code.
Thanks

**Comment by davoiceamplesense** [comment]
Just a quick note for other devs facing similar issues with child contracts. 

Up until at last October 2020, verifying child contracts was not possible via Etherscan. 

This post indicates that it _may_ be possible, our experience today confirms it. 

For others seeking guidance on this issue, this discussion outlines the years-long problem with this issue and this issue confirms it has been solved. 

Placing this here for reference: https://ethereum.stackexchange.com/a/87962

**Comment by Lopesptpt** [comment]
Looking forward to see the progress on the kMPL/AMPL Uniswap pair! Exciting times ahead

**Comment by blogginjesus** [comment]
Did I understand it right that the normal pools lile zeus are not infected by this issue ? Is it safe to provide to Eth/Ampl to zeus to farm kmpl ??

**Comment by davoiceamplesense** [comment]
Hi @blogginjesus: You sent me a message asking this question on our Community Hub. I replied there.

**Comment by Lopesptpt** [comment]
Maybe you could elaborate your response here so other people can see it too.

**Comment by blogginjesus** [comment]
Davoice answered: 
"Thanks. We’re using the kGeyser contracts that are based on the audited Geyser contracts developed by the Ampleforth team.

The discussion about security on ACCP-003 was related to the contracts not having the green checkmark on them due to the fact that it was previously not possible to verify child contracts (spawned by the original contracts) on Etherscan.

This is possible now (as of October), and the contracts have been verified. 

Currently, it’s easier to mine kMPL using the Zeus pool, so we recommend new miners start with that one."

**Comment by GiraeffleAeffle** [comment]
So does that mean that I didn't get any rebase when I provided liquidity to the AMPL/kMPL pair? If that is the case, that's really bad.

**Comment by davoiceamplesense** [comment]
@GiraeffleAeffle: All AMPL rebases.  

@blogginjesus: thanks for sharing my response.

**Comment by GiraeffleAeffle** [comment]
@davoiceamplesense But as described in the blogpost from Brandon [here](https://www.ampltalk.org/app/forum/technology-development-17/topic/supported-dex-pools-61/) it is possible that it is out of sync now and that the balance is wrong as far as I understood. Why didnt you use the pools that have the native support from the beginning like mentioned in the post?

**Comment by davoiceamplesense** [comment]
@GiraeffleAeffle: Thanks for your question. 

It comes down to a lack of clarity regarding the situation with AMPL/XXX token pools on Uniswap and the process of securing approval for the sync() function for AMPL/XXX pairs on Uniswap. 

Once this ACCP is implemented (and all indications are that it will be implemented soon), we will be publishing an overview of this process and supplemental resources for other teams seeking to create AMPL/XXX pairs on DEXs, to help educate developers and provide additional clarity.

**Comment by davoiceamplesense** [comment]
@brandoniles: Hope you had a good weekend. 

The contract verification issue you asked about was resolved on Friday. is there anything else required from us prior to implementation? 

Thank you.

**Comment by nithinkrishna** [comment]
The [orchestrator](https://github.com/ampleforth/uFragments/commit/fb6eab6ad37b891158dcd280b250baecc5f8fc25) was built to atomically notify downstream platforms about rebase execution, and is part of the core Ampleforth protocol. The transactions which are added to the Orchestrator are part of Ampleforth's `rebase` transaction. 

My personal perspective is that only transactions which are considered **core to the protocol's function** should be added to the Orchestrator. 

I see there being 3 primary kinds of transactions proposed to be added Orchestrator. 
Here's my rationale on which ones should be added and which ones should not.

1. **Core protocol functionality**: Must be part of the Orchestrator. Multi-chain AMPL is one such example. The orchestrator on the master chain would notify various bridges contracts about rebase which would be propagated through to downstream sub-chains. When we do integrate with bridges and other-chains, bridge notification transactions should added as they are an extension of the protocol itself.

2. **Supporting AMPL liquidity and direct utilization of AMPL**: Can be part of the Orchestrator for now, but eventually should not be. Earlier this year (Apr/May) when some of the 2nd gen AMMs like UniswapV2 and Balancer were launching, Elastic tokens weren't as common as they are now. A lot of these platforms when built didn't account for the behavior elastic tokens. So they needed to be explicitly 'synced' on rebase, to prevent attackers from draining value from the underlying liquidity pools. As more elastic tokens come about, newer versions of these platforms and newer platforms would account for elastic tokens. As of now we have 4 such transactions, `Sync` calls on the Uniswap/Sushiswap ETH-AMPL pools and `Gulp` calls on the Balancer AMPL-USDC and AMPL-ETH-WBTC pools. Combined liquidity across these pools ~36M$ (as of now). A 1% rebase would let the attacker skim around 360K from LPs. As and when liquidity migrates to these newer platforms which support elastic tokens we should remove these transactions (category 2) from the orchestrator whenever it's safe to do so, as they aren't part of the core protocol. 

3. **Supporting the AMPL eco-system**: Should not be part of the Orchestrator.

***

I think support for Eco system projects is very important. However, I feel altering the protocol's core function to do so might not be a wise decision in the near-term or the long-term. 

With regard to the current situation with this particular project, I understand the predicament. Since the token being discussed has ~70 holders, you could trivially  perform a 1:1 token migration and continue your program on a Mooniswap pool which natively supports elastic tokens.

**Comment by davoiceamplesense** [comment]
Thanks to everyone for their participation in this conversation. 

@brandoniles: We are officially withdrawing ACCP-03 from consideration. 

**Those interested in our follow-up regarding this issue can find a detailed post [about it here]**(https://forum.amplesense.io/resetting-the-zeus-and-apollo-kgeysers-why-how-and-whats-next/).

**Comment by OrphanedBlock** [comment]
~70 holders is not enough for this to warrant approval. There are opportunity costs and resource strains to execute on something. The resource strain and opportunity cost of doing this for something that isn't supported by many participants does not make sense when there is such important work to be done on the Ampleforth project. 

Other solutions such as the 1:1 migration to Mooniswap make more sense.

Additionally, there is a problem with how the kMPL / AMPL Uniswap pool  and the way the Amplesense DAO is conducting themselves.

First, they did not understand the technology and rolled it out. This is 100% the fault of the Amplesense DAO. Mistakes can sometimes be OK, as long as they do not result in the loss of funds or some other irrecoverable/fatal manner. However, the fact that the Amplesense DAO is doing what seems like everything but admitting their mistake is of poor character. Combined with the fact that those running the "DAO" are anonymous except for 1 person, leads to question marks.

Second, when there is a problem with something, particularly when it requires contributing user funds, it is extremely irresponsible to continue to allow users to contribute their funds. It is an even graver error of character and execution to continue to promote and seek additional contributors and participants. The Apollo "Geyser" has no warning attached and no admission of a problem, even though the Amplesense DAO is fully aware of a major issue with their Apollo incentive program, so much so that they have submitted an AIP for help from the actual AMPL engineers. 

Third, it appears the Amplesense Dao is deliberately working to capitalize on the name and branding of Ampleforth and the Ampleforth official Geysers. It is doing so in a very deceptive manner. Many people are confused because the Amplesense Dao has intentionally used the Ampleforth branding, nomiclature and all social channels. It is difficult to differentiate between the official Ampleforth items and the community lead Amplesense Dao items. More clarification from the Amplesense team is needed. The Amplesense team should cease using all of the AMPL names, brands and terms like Geyser. 

Fourth, The Amplesense DAO is not actually a DAO. This is also deceptive

This ACCP-3 proposal should not be supported. 

The best option for the non-affiliated Amplesense team to solve their issue, which is unrelated to official Ampleforth is to do a token migration to Mooniswap. This would be the best choice and in line with what Amplesense DAO claims as their mission. The Amplesense DAO claims to wish to support Ampleforth and establishing their Apollo incentive program on Mooniswap, and not taxing the Ampleforth engineering team for a fix would be the best way to achieve that goal of support for Ampleforth protocol.
