### ISSUE TITLE
ACCP-4 Discussion: Ethereum Scaling Solution Proposal for Future Ampleforth Geysers

### ISSUE THREAD

**Issue by CharmOffnz** [ampleforth/AIPs#28]
SIMPLE SUMMARY

A layer 2 scaling solution for the AMPL/WETH geyser program via an Ethereum layer 2 protocol is proposed to address high gas fees on the Ethereum network for the purpose of lowering the barrier to entry and supporting adoption of Ampleforth as a base money, store of value and unit of exchange.

ABSTRACT

Ethereum gas fees are a significant entry barrier to new market participants and will likely become a financial burden to existing AMPL hodlers given the projected network congestion that will follow increased activity as the cryptocurrency marketcap substantially increases in 2021.
The recent announcement of Ampleforth’s cross-chain integration with Tron, Polkadot, and NEAR blockchains is a step forward in providing more economical options for AMPL hodlers to engage with the ecosystem.
However, the majority of decentralized borrowing, lending and trading occurs on the Ethereum blockchain as of 2020, and a solution for decreasing transaction costs should be a high priority for the team. The Ampleforth protocol should provide support for transactions on layer 2 networks such as xDai, MATIC or Loopring to bridge the gap in low-cost transaction services until Ethereum 2.0 scaling is implemented.

MOTIVATION

Ampleforth is one of the leading innovative blockchains in cryptocurrency, and the geysers are arguably the most important tools in growing the Ampleforth ecosystem. Once the gas fees become too high, however, there will be a massive loss in potential new hodlers and LPs. The motivation is to keep the community growing and define Ampleforth’s position as a core primitive digital asset alongside BTC and ETH.
With a layer 2 protocol, for example xDai, AMPL hodlers can pair AMPL/WETH on a Uniswap-like DEX called Honeyswap for a future geyser program to lower the entry barrier for average market participants. To improve decentralization of the network, the layer 2 network solution for AMPL/WETH LP could be decided by community vote and discussion to expand support for either:
-xDai network for honeyswap.exchange
-MATIC network for quickswap.exchange
-Loopring network for exchange.loopring.io
The selected Ethereum L2 solution should prioritize accessibility, depth of liquidity and security. The Ampleforth protocol can continue to lead in innovation within the crypto space by driving adoption for Ethereum L2 DEXs by utilizing the popular geyser programs.

**Comment by seldamat** [comment]
Layer II solutions will become more commonplace as part of Eth 2.0 scaling and widespread adoption continues. The entry barrier for market participants can be substantially lowered by keeping gas costs negligible compared to the transaction size. 

Individuals have already begun using xDAI/honeyswap, which may be a source of Ampl "supply leak" since ampls on xdai side chain are not included in the rebase. This is a low incidence event currently, but we may see more usage of xDAI side chain in the very near future.

I support a mid-term (3-6 month) prioritization of this solution for future geyser programs to address gas costs, any potential xdai supply leak, and lowering the entry barrier for market participation and micro-transactions with ampl.

**Comment by CharmOffnz** [comment]
#27 **Please note that the correct Honeyswap Exchange URL is honeyswap.org/**
